### PR TITLE
Feature/skale 1253 rpc stats

### PR DESCRIPTION
**Pull request by sergiy-skalelabs**

### CODE REVIEW

**Comment by DimaStebaev** [comment]
What is difference with https://github.com/skalenetwork/skaled/pull/55?

**Comment by sergiy-skalelabs** [comment]
> difference
1) @cstrangedk asked to fix missing `;` at the end of **libweb3jsonrpc/SkaleStats.json** nevertheless other JSON files in same folder does not end with `;` - codacy hates only this file just because no `;` at end
2) Unable to merge even after adding `;` to end
3) I found error in the `skale_stats` signature definition in  **libweb3jsonrpc/SkaleStats.json** - so, this JSON is new now

**Comment by dimalit** [comment]
I propose to add some kind of error report when there are no such methods on endpoint (for stats)

**Comment by sergiy-skalelabs** [comment]
Bad/unknown RPC method error is returned by **geth**

**Comment by dimalit** [comment]
> Bad/unknown RPC method error is returned by **geth**

and by wrong build of skaled

**Comment by sergiy-skalelabs** [comment]
> and by wrong build of skaled
**YES**

**Review by dimalit — APPROVED** [review]

**Pull request merged**
