### PR TITLE
SKALE-3855 ECDSA sign/verify for IMA tracker messages

### PR DESCRIPTION
**Pull request by sergiy-skalelabs**
ECDSA sign/verify for IMA tracker messages

### CODE REVIEW

**Review by dimalit — COMMENTED** [review]
So, will merge after latest fixes?

**Comment by sergiy-skalelabs** [comment]
> So, will merge after latest fixes?

yes, sure

**Comment by dimalit** [comment]
Decided to merge it later

**Comment by sergiy-skalelabs** [comment]
re-created as part of https://github.com/skalenetwork/skaled/pull/566

**Pull request closed without merging**
