### PR TITLE
SKALE-1532 memory leaks fixes

### PR DESCRIPTION
**Pull request by sergiy-skalelabs**
- fixed very bad data races in transaction cache( removed m_transaction_cache, added m_safe_transaction_cache with set of safe access APIs)
- fixed very bad data race corrupting set of known transactions in transaction cache (the TransactionQueue::knownTransactions() method is completely incorrect and does damage)
- fixed many small data races with bool flags and numeric counters (replaced with std::atomic)
- fixed data race in statistics computation code
- fixed data race in logs bloom data access. read guard lock was used for writing data
- fixed data race in State class describing SKALE state
- fixed data race in SkaleDebug*** debugging interface classes
- fixed data race in set of received from consensus transactions
- in consensus - fixed data race of message queue containing dynamic pointers to message envelopes
- in consensus - fixed misaligned address use in NTP server connection code
- no new and non-tested functions/classed added
- no new tests required

### CODE REVIEW

**Review by cstrangedk — DISMISSED** [review]

**Comment by DimaStebaev** [comment]
Please pass all required checks.

**Review by dimalit — DISMISSED** [review]
No-no-no, not now! I need time (and ticket) to review it very carefully!
(or we can revive https://skalelabs.atlassian.net/browse/SKALE-1372 )

**Comment by sergiy-skalelabs** [comment]
> No-no-no, not now! I need time (and ticket) to review it very carefully!
> (or we can revive https://skalelabs.atlassian.net/browse/SKALE-1372 )

We have no much time. I need memory leak fixes today. Eugene need them.
This must be merged today as soon as possible

**Comment by dimalit** [comment]
> We have no much time. I need memory leak fixes today. Eugene need them.
> This must be merged today as soon as possible

Codeowners, of course, can decide. But I do not support so quick and untested merge. Can build docker container from feature branch.

**Comment by kladkogex** [comment]
Guys - lets  pause this until I come back and understand what is going on.

In general it is Dima Litvinov's area, and he is the code owner of this.
We do not want to do anything fast in there.

**Comment by kladkogex** [comment]
Also please make separate pull requests - one in consensus and one in skaled

**Comment by sergiy-skalelabs** [comment]
> Also please make separate pull requests - one in consensus and one in skaled

I did, this one contain only skaled changes + reference to consensus - only reference

**Comment by sergiy-skalelabs** [comment]
> Also please make separate pull requests - one in consensus and one in skaled

I will. Sure. But Eugene is blocked with memory leak testing and my last 2 memory leak fixing tasks are paused too.

**Pull request closed without merging**
