### PR TITLE
Feature/skale 1516 finalizing fast snapshot distribution system

### PR DESCRIPTION
**Pull request by sergiy-skalelabs**

### CODE REVIEW

**Review by dimalit — DISMISSED** [review]
Decided to refactor together (Serge and me)

**Review by kladkogex — DISMISSED** [review]

**Review by kladkogex — DISMISSED** [review]

**Review by dimalit — DISMISSED** [review]
I'd split this into 3 pull requests:
1. Changes to config options (ChainParams)
2. Changes to HTTP/WS server (certificates etc)
3. Implementation of snapshot download

**Comment by sergiy-skalelabs** [comment]
> I'd split this into 3 pull requests:
> 
> 1. Changes to config options (ChainParams)
> 2. Changes to HTTP/WS server (certificates etc)
> 3. Implementation of snapshot download

Good idea, but I have no time for this

**Comment by cstrangedk** [comment]
Closing PR, please split into separate PRs for cleaner review

**Pull request closed without merging**
